# Generated by Django 4.2.30 on 2026-04-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocessor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingresult',
            name='cleaning_after',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processingresult',
            name='cleaning_before',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
