# Generated by Django 4.2.30 on 2026-04-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocessor', '0002_processingresult_cleaning_after_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingresult',
            name='cleaning_diff',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
